name: CI Builds

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: write
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build with Maven
        run: mvn --batch-mode --no-transfer-progress verify -Pcoverage -Dgpg.skip=true

      - name: SonarQube Scan
        if: github.event_name != 'pull_request'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          mvn --batch-mode --no-transfer-progress \
            org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Pcoverage \
            -Dgpg.skip=true \
            -Dsonar.token=${SONAR_TOKEN} \
            -Dsonar.host.url=${SONAR_HOST_URL} \
            -Dsonar.branch.name=${GITHUB_REF_NAME}

      - name: SonarQube Scan-PRs
        if: github.event_name == 'pull_request'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          PR_BRANCH: ${{ github.head_ref }}
          PR_BASE: ${{ github.base_ref }}
          PR_ID: ${{ github.event.pull_request.number }}
        run: |
          mvn --batch-mode --no-transfer-progress \
            org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Pcoverage \
            -Dgpg.skip=true \
            -Dsonar.token=${SONAR_TOKEN} \
            -Dsonar.host.url=${SONAR_HOST_URL} \
            -Dsonar.pullrequest.key=$PR_ID \
            -Dsonar.pullrequest.branch=$PR_BRANCH \
            -Dsonar.pullrequest.base=$PR_BASE
